import turtle as trtl
import random

painter = trtl.Turtle()

colors = ['#FF0000','#FF7F00','#FFFF00','#C0C0C0','#808080','#000000','#800000','#808000','#00FF00','#008000','#00FFFF','#008080','#0000FF','#000080','#FF00FF','#800080']

painter.color(random.choice(colors))
painter.begin_fill()
painter.forward(100)
painter.left(90)
painter.color(random.choice(colors))
painter.forward(100)
painter.left(90)
painter.color(random.choice(colors))
painter.forward(100)
painter.left(90)
painter.color(random.choice(colors))
painter.forward(100)
painter.end_fill()
painter.color(random.choice(colors))
painter.penup()
painter.goto(25,0)
painter.left(180)
painter.pendown()
painter.forward(25)
painter.right(90)
painter.color(random.choice(colors))
painter.forward(25)
painter.color(random.choice(colors))
painter.right(90)
painter.forward(25)
painter.left(90)
painter.color(random.choice(colors))
painter.forward(25)
painter.end_fill
painter.color(random.choice(colors))
painter.penup()
painter.goto(50,0)
painter.pendown()
painter.forward(25)
painter.left(90)
painter.color(random.choice(colors))
painter.forward(25)
painter.left(90)
painter.color(random.choice(colors))
painter.forward(25)
painter.penup()
painter.goto(0,100)
painter.right(135)
painter.pendown()
painter.begin_fill()
painter.color(random.choice(colors))
painter.forward(70)
painter.right(90)
painter.color(random.choice(colors))
painter.forward(70)
painter.end_fill()
painter.penup()
painter.goto(40,75)
painter.pendown()
painter.begin_fill()
painter.color(random.choice(colors))
painter.circle(10)
painter.end_fill()
painter.penup()
painter.goto(200,0)
painter.left(45)
painter.begin_fill()
painter.color(random.choice(colors))
painter.forward(30)
painter.left(90)
painter.color(random.choice(colors))
painter.forward(40)
painter.left(90)
painter.color(random.choice(colors))
painter.forward(30)
painter.left(90)
painter.color(random.choice(colors))
painter.forward(40)
painter.end_fill()
painter.penup()
painter.goto(180,40)
painter.left(90)
painter.pendown()
painter.begin_fill()
painter.color(random.choice(colors))
painter.forward(70)
painter.left(100)
painter.color(random.choice(colors))
painter.forward(160)
painter.end_fill()
painter.penup()

window = trtl.Screen()
window.bgcolor(random.choice(colors))
window.mainloop()